name: "PHP"

on: # yamllint disable-line rule:truthy
    pull_request:
        paths:
            - ".github/workflows/ci-php.yaml"
            - "**"
    push:
        branches:
            - "develop"
            - "master"
        paths:
            - ".github/workflows/ci-php.yaml"
            - "**"

env:
    BOT_EMAIL: "silasjoisten@gmail.com"
    BOT_NAME: "Silas Joisten"
    REQUIRED_PHP_EXTENSIONS: "ctype, filter, hash, iconv, json"

jobs:
    coding-standards:
        name: "Coding Standards"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.0"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2.4.0"

            -
                name: "Install PHP with extensions"
                uses: "shivammathur/setup-php@2.15.0"
                with:
                    coverage: "none"
                    extensions: "${{ env.REQUIRED_PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: "composer:v2"

            -
                name: "Validate composer.json"
                run: "composer validate"

            -
                name: "Install dependencies with composer"
                uses: "ramsey/composer-install@1.3.0"
                with:
                    composer-options: "--no-scripts"
            -
                name: "Create cache directory for friendsofphp/php-cs-fixer"
                run: "mkdir -p .build/php-cs-fixer"

            -
                name: "Cache cache directory for friendsofphp/php-cs-fixer"
                uses: "actions/cache@v3.0.8"
                with:
                    path: ".build/php-cs-fixer"
                    key: "php-${{ matrix.php-version }}-php-cs-fixer-${{ github.sha }}"
                    restore-keys: "php-${{ matrix.php-version }}-php-cs-fixer-"

            -
                name: "Run friendsofphp/php-cs-fixer"
                run: "vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --verbose"

            -
                name: "Commit files fixed with friendsofphp/php-cs-fixer"
                uses: "stefanzweifel/git-auto-commit-action@v4.14.1"
                with:
                    branch: "${{ github.head_ref }}"
                    commit_author: "${{ env.BOT_NAME }} <${{ env.BOT_EMAIL }}>"
                    commit_message: "Fix: Run 'php-cs-fixer fix'"
                    commit_user_email: "${{ env.BOT_EMAIL }}"
                    commit_user_name: "${{ env.BOT_NAME }}"

    tests:
        name: "Tests"

        runs-on: "ubuntu-latest"

        env:
            APP_ENV: "test"

        strategy:
            matrix:
                php-version:
                    - "8.0"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2.4.0"

            -
                name: "Install PHP with extensions"
                uses: "shivammathur/setup-php@2.15.0"
                with:
                    coverage: "pcov"
                    extensions: "${{ env.REQUIRED_PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: "composer:v2"

            -
                name: "Install dependencies with composer"
                uses: "ramsey/composer-install@1.3.0"
                with:
                    composer-options: "--no-scripts"

            -
                name: "Run unit tests with phpunit/phpunit"
                run: "SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/phpunit --testsuite=tests --coverage-clover=.build/phpunit/coverage-unit.xml"
